model_path: "../../../experiments/Potsdam/no_rough_001"
checkpoint: "latest"
base_model_name_or_path: "../../../weight/stable-diffusion-v1-5"
label_embed_dir: "../../../weight/labelembednet8"
data_dir: "../../../examples/Potsdam"
metadata_file: "metadata_i2s_segformer_test.jsonl"
dataset: "../../datasets/Potsdam/test.yaml"
output_dir: "../../../predictions/Potsdam/no_rough_001"
batch_size: 1
dataloader_num_workers: 2
num_inference_steps: 25
guidance_scale: 3.0
strength: 1.0
prompt: ""
negative_prompt: null
use_dataset_text: true
seed: 42
max_samples: null
skip_existing: true
