type: "I2SDataset"
num_classes: 6
load_rough: true
load_text: true
train: false
pipeline:
  - type: "ResizeI2S"
    size: 512
    keys: ["image", "rough_label_index"]
  - type: "ToTensorI2S"
  - type: "NormalizeImage"
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
  - type: "ToLongTensorI2S"
    keys: ["rough_label_index"]
