model_path: "../../../experiments/CHN6-CUG/segformer_cubic_001"
checkpoint: "latest"
base_model_name_or_path: "../../../weight/stable-diffusion-v1-5"
label_embed_dir: "../../../weight/labelembednet2"
data_dir: "../../../examples/CHN6-CUG"
metadata_file: "metadata_i2s_segformer_test.jsonl"
dataset: "../../datasets/CHN6-CUG/test.yaml"
output_dir: "../../../predictions/CHN6-CUG/segformer_cubic_001"
batch_size: 1
dataloader_num_workers: 2
num_inference_steps: 25
guidance_scale: 3.0
strength: 1.0
prompt: ""
negative_prompt: null
use_dataset_text: true
seed: 42
max_samples: null
skip_existing: true
